# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-06-20 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform_actuel', '0002_document_content_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='content_doc',
        ),
        migrations.AddField(
            model_name='fichier',
            name='content_doc',
            field=models.TextField(null=True),
        ),
    ]
