# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-24 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform_actuel', '0003_auto_20170620_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_photo', models.CharField(blank=True, max_length=50, null=True)),
                ('url_photo', models.ImageField(null=True, upload_to='photos/')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_movie', models.CharField(blank=True, max_length=50, null=True)),
                ('url_movie', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
