# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-09-24 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform_actuel', '0004_photo_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='titre_movie',
            new_name='titre_video',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='url_movie',
            new_name='url_video',
        ),
    ]
